version: '3.7'

services:

  jetty-ring:
    image: jetty-ring-backend
    container_name: books_jetty_ring
    build:
      context: .
      dockerfile: jetty-ring-dockerfile
    environment:
      DATABASE_URL: database
    depends_on:
      - database
    ports:
      - "3000:8080"

  database:
    image: postgres:13.4
    restart: always
    container_name: books_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 3ZmW9M38mX8AQGqBP
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    container_name: books_adminer
    ports:
      - "8080:8080"


  mongo-database:
    image: mongo:4.2
    restart: always
    container_name: mongo-books
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GJabLafh53j4LL
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017-27019:27017-27019"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - database
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: GJabLafh53j4LL
      ME_CONFIG_MONGODB_SERVER: mongo-books
      # Do I need a normal user here?
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: ihavealongpassword

volumes:
  mongo-data: {}
  db-data: {}
