(ns bookstore.import.amazon-test
  (:require [clojure.test :refer :all])
  (:require [bookstore.import.amazon :refer [import-wishlist]]))

(deftest ^:amazon import-wishlist-test
  (is (= (#:amazon.books{:description             "Facebook's algorithms shaping the news. Self-driving cars roaming the streets. Revolution on Twitter and romance on Tinder. We live in a world constructed of code--and coders are the ones who built it for us. Programmers shape our everyday behavior: When they make something easy to do, we do more of it. When they make it hard or impossible, we do less of it. From acclaimed tech writer Clive Thompson comes a brilliant anthropological reckoning with the most powerful tribe in the world today, computer programmers, in a book that interrogates who they are, how they think, what qualifies as greatness in their world, and what should give us pause. In pop culture and media, the people who create the code that rules our world are regularly portrayed in hackneyed, simplified terms, as ciphers in hoodies. Thompson goes far deeper, taking us close to some of the great programmers of our time, including the creators of Facebook's News Feed, Instagram, Google's cutting-edge AI, and more. Speaking to everyone from revered \"10X\" elites to neophytes, back-end engineers and front-end designers, Thompson explores the distinctive psychology of this vocation--which combines a love of logic, an obsession with efficiency, the joy of puzzle-solving, and a superhuman tolerance for mind-bending frustration. Along the way, Coders ponders the morality and politics of code, including its implications for civic life and the economy and the major controversies of our era. In accessible, erudite prose, Thompson unpacks the surprising history of the field, beginning with the first coders -- brilliant and pioneering women, who, despite crafting some of the earliest personal computers and programming languages, were later written out of history. At the same time, the book deftly illustrates how programming has become a marvelous new art form--a source of delight and creativity, not merely danger. To get as close to his subject as possible, Thompson picks up the thread of his own long-abandoned coding skills as he reckons, in his signature, highly personal style, with what superb programming looks like. To understand the world today, we need to understand code and its consequences. With Coders, Thompson gives a definitive look into the heart of the machine.",
                         :amazon-thumbnail-url    "https://m.media-amazon.com/images/I/516yOG7tZ4L._SS135_.jpg",
                         :publisher               "Penguin Books; Reprint Auflage (24. März 2020)",
                         :item-added-date         "Artikel hinzugefügt 9. April 2020",
                         :isbn-13                 "978-0735220584",
                         :title                   "Coders: The Making of a New Tribe and the Remaking of the World (Englisch) Taschenbuch – 24. März 2020",
                         :isbn-10                 "0735220581",
                         :language                "Englisch",
                         :amazon-id               "I2V9EWL9YVXPTY",
                         :amazon-book-image-front "https://images-na.ssl-images-amazon.com/images/I/51oBALi69OL._SY344_BO1,204,203,200_.jpg",
                         :book-length             "448 Seiten",
                         :authors                 ["Clive Thompson"],
                         :amazon-url              "https://www.amazon.de/Coders-Making-Tribe-Remaking-World/dp/0735220581/ref=tmm_pap_title_0?_encoding=UTF8&coliid=I2V9EWL9YVXPTY&colid=2Y2U31UCNA1ME&qid=&sr=",
                         :price                   ""}
           #:amazon.books{:description             "\"Design is a way to engage with real content, real experience,\" writes celebrated essayist Michael Bierut in this follow-up to his best-selling Seventy-Nine Short Essays on Design (2007). In more than fifty smart and accessible short pieces from the past decade, Bierut engages with a fascinating and diverse array of subjects. Essays range across design history, practice, and process; urban design and architecture; design hoaxes; pop culture; Hydrox cookies, Peggy Noonan, baseball, The Sopranos; and an inside look at his experience creating the \"forward\" logo for Hillary Clinton's 2016 presidential campaign. Other writings celebrate such legendary figures as Jerry della Femina, Alan Fletcher, Charley Harper, and his own mentor, Massimo Vignelli. Bierut's longtime work in the trenches of graphic design informs everything he writes, lending depth, insight, and humor to this important and engrossing collection.",
                          :amazon-thumbnail-url    "https://m.media-amazon.com/images/I/41vZOzm8+aL._SS135_.jpg",
                          :publisher               "PRINCETON ARCHITECTURAL PR; 01 Auflage (7. November 2017)",
                          :item-added-date         "Artikel hinzugefügt 9. April 2020",
                          :isbn-13                 "978-1616896249",
                          :title                   "Now You See It and Other Essays on Design (Englisch) Gebundene Ausgabe – 7. November 2017",
                          :isbn-10                 "1616896248",
                          :language                "Englisch",
                          :amazon-id               "IGECR2MGXNLUO",
                          :amazon-book-image-front "https://images-na.ssl-images-amazon.com/images/I/51rj-8gPSOL._SY344_BO1,204,203,200_.jpg",
                          :book-length             "240 Seiten",
                          :authors                 ["Michael Bierut"],
                          :amazon-url              "https://www.amazon.de/Now-You-Other-Essays-Design/dp/1616896248/ref=tmm_hrd_title_0?_encoding=UTF8&coliid=IGECR2MGXNLUO&colid=2Y2U31UCNA1ME&qid=&sr=",
                          :price                   ""}
           #:amazon.books{:description             "The similarities between madness and modernism are striking: defiance of convention, nihilism, extreme relativism, distortions of time, strange transformations of self, and much more. In this revised edition of a now classic work, Louis Sass, a clinical psychologist, offers a radically new vision of schizophrenia, comparing it with the works of such artists and writers as Kafka, Beckett, and Duchamp, and considering the ideas of philosophers including Nietzsche, Heidegger, Foucault, and Derrida. Here is a highly original portrait of the world of insanity, along with a provocative commentary on modernist and postmodernist culture.",
                          :amazon-thumbnail-url    "https://m.media-amazon.com/images/I/418HwSEi9DL._SS135_.jpg",
                          :publisher               "Oxford University Press; Revised Auflage (31. Oktober 2017)",
                          :item-added-date         "Artikel hinzugefügt 9. April 2020",
                          :isbn-13                 "978-0198779292",
                          :title                   "Madness and Modernism: Insanity in the light of modern art, literature, and thought (revised edition) (International Perspectives in Philosophy and Psychiatry) (Englisch) Taschenbuch – 31. Oktober 2017",
                          :isbn-10                 "0198779291",
                          :language                "Englisch",
                          :amazon-id               "IAKICSUW9R9O7",
                          :amazon-book-image-front "https://images-na.ssl-images-amazon.com/images/I/418HwSEi9DL._SY344_BO1,204,203,200_.jpg",
                          :book-length             "556 Seiten",
                          :authors                 ["Louis Sass"],
                          :amazon-url              "https://www.amazon.de/dp/0198779291/?coliid=IAKICSUW9R9O7&colid=2Y2U31UCNA1ME&psc=1&ref_=lv_vv_lig_dp_it",
                          :price                   "42,86 €"}
           #:amazon.books{:description             "Als sein Vater stirbt, reist Didier Eribon zum ersten Mal nach Jahrzehnten in seine Heimatstadt. Gemeinsam mit seiner Mutter sieht er sich Fotos an – das ist die Ausgangskonstellation dieses Buchs, das autobiografisches Schreiben mit soziologischer Reflexion verknüpft. Eribon realisiert, wie sehr er unter der Homophobie seines Herkunftsmilieus litt und dass es der Habitus einer armen Arbeiterfamilie war, der es ihm schwer machte, in der Pariser Gesellschaft Fuß zu fassen. Darüber hinaus liefert er eine Analyse des sozialen und intellektuellen Lebens seit den fünfziger Jahren und fragt, warum ein Teil der Arbeiterschaft zum Front National übergelaufen ist. Das Buch sorgt seit seinem Erscheinen international für Aufsehen. So widmete Édouard Louis dem Autor seinen Bestseller »Das Ende von Eddy«.",
                          :amazon-thumbnail-url    "https://m.media-amazon.com/images/I/41j7s4VLyIL._SS135_.jpg",
                          :publisher               "Suhrkamp Verlag; Deutsche Erstausgabe Auflage (8. Mai 2016)",
                          :item-added-date         "Artikel hinzugefügt 9. April 2020",
                          :isbn-13                 "978-3518072523",
                          :title                   "Rückkehr nach Reims (edition suhrkamp) (Französisch) Taschenbuch – 8. Mai 2016",
                          :isbn-10                 "3518072528",
                          :language                "Französisch",
                          :amazon-id               "IO8WXJVOH1KSY",
                          :amazon-book-image-front "https://images-na.ssl-images-amazon.com/images/I/41YkCZm-81L._SX298_BO1,204,203,200_.jpg",
                          :book-length             "240 Seiten",
                          :authors                 ["Didier Eribon"],
                          :amazon-url              "https://www.amazon.de/R%C3%BCckkehr-Reims-suhrkamp-Didier-Eribon/dp/3518072528/ref=tmm_pap_title_0?_encoding=UTF8&coliid=IO8WXJVOH1KSY&colid=2Y2U31UCNA1ME&qid=&sr=",
                          :price                   ""}
           #:amazon.books{:amazon-id            "I2TLC3W2GU1TRB",
                          :title                "Man's Search for Meaning by Frankl, Viktor E. (2006) Taschenbuch",
                          :amazon-url           nil,
                          :amazon-thumbnail-url "https://images-na.ssl-images-amazon.com/images/G/01/x-locale/communities/wishlist/no_image_2x._CB485924800_SS135_.png",
                          :item-added-date      "Artikel hinzugefügt 9. April 2020",
                          :price                ""}
           #:amazon.books{:description             "'A statistical national treasure' Jeremy Vine, BBC Radio 2 'Required reading for all politicians, journalists, medics and anyone who tries to influence people (or is influenced) by statistics. A tour de force' Popular Science Do busier hospitals have higher survival rates? How many trees are there on the planet? Why do old men have big ears? David Spiegelhalter reveals the answers to these and many other questions - questions that can only be addressed using statistical science. Statistics has played a leading role in our scientific understanding of the world for centuries, yet we are all familiar with the way statistical claims can be sensationalised, particularly in the media. In the age of big data, as data science becomes established as a discipline, a basic grasp of statistical literacy is more important than ever. In The Art of Statistics, David Spiegelhalter guides the reader through the essential principles we need in order to derive knowledge from data. Drawing on real world problems to introduce conceptual issues, he shows us how statistics can help us determine the luckiest passenger on the Titanic, whether serial killer Harold Shipman could have been caught earlier, and if screening for ovarian cancer is beneficial. 'Shines a light on how we can use the ever-growing deluge of data to improve our understanding of the world' Nature",
                          :amazon-thumbnail-url    "https://m.media-amazon.com/images/I/41avZxZMM4L._SS135_.jpg",
                          :publisher               "Pelican (13. Februar 2020)",
                          :item-added-date         "Artikel hinzugefügt 9. April 2020",
                          :isbn-13                 "978-0241258767",
                          :title                   "The Art of Statistics: Learning from Data (Pelican Books) (Englisch) Taschenbuch – 13. Februar 2020",
                          :isbn-10                 "0241258766",
                          :language                "Englisch",
                          :amazon-id               "I372TIWCEA46BO",
                          :amazon-book-image-front "https://images-na.ssl-images-amazon.com/images/I/41ZPzDG7cQL._SY344_BO1,204,203,200_.jpg",
                          :book-length             "448 Seiten",
                          :authors                 ["David Spiegelhalter"],
                          :amazon-url              "https://www.amazon.de/Learning-Data-Statistics-Pelican-Books/dp/0241258766/ref=tmm_pap_title_0?_encoding=UTF8&coliid=I372TIWCEA46BO&colid=2Y2U31UCNA1ME&qid=&sr=",
                          :price                   ""})
         (import-wishlist "https://www.amazon.de/hz/wishlist/ls/2Y2U31UCNA1ME"))))
