name: Build + Deploy
#description: 'Build and deploy to my DigitalOcean droplet'

on:
  push:
    branches:
      - github-actions-test

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Run tests (lein test)
        run: lein test


  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup DigitalOcean Private Key for SSH and SCP Access
        env:
          DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS: ${{ secrets.DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS }}
        run: |
          mkdir ~/.ssh
          echo "$DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Build uberjar file
        run: |
          lein ring uberjar

      - name: Using SCP, load uberjar and Dockerfile to DigitalOcean droplet
        run: |
          scp -o StrictHostKeyChecking=no target/*-standalone.jar Dockerfile dominik@165.22.76.70:/home/dominik

      - name: Using SSH, stop old container, build and run new ring-books server
        env:
          docker_stop: 'if [[ -f container_id ]] ; then docker stop $(cat container_id) ; rm ./container_id ; fi'
          ls_and_pwd: 'ls -a && pwd'
          docker_build: 'docker build -t ring-books .'
          docker_run: 'docker run --rm --cidfile container_id -p 3000-3001:3000-3001 -d ring-books'
        run: |
          ssh -o StrictHostKeyChecking=no dominik@165.22.76.70 "$docker_stop && $ls_and_pwd && $docker_build && $docker_run"

# Next steps for Github Actions:
# - MongoDB server is still missing --> docker compose!
# - at some point: also build the frontend
# - also include some tests!


