name: Build + Deploy
#description: 'Build and deploy to my DigitalOcean droplet'

on:
  push:
    branches:
      - github-actions-test

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup DigitalOcean Private Key for SSH and SCP Access
        env:
          DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS: ${{ secrets.DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS }}
        run: |
          mkdir ~/.ssh
          echo "$DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Build uberjar file
        run: |
          lein ring uberjar

      - name: Using SCP, load ring-books-container to DigitalOcean droplet
        run: |
          scp -o StrictHostKeyChecking=no target/*-standalone.jar Dockerfile dominik@165.22.76.70:/home/dominik

      - name: Using SSH, stop old container, build and run new ring-books server
        run: |
          ssh -o StrictHostKeyChecking=no dominik@165.22.76.70 \
            docker stop $(cat container_id) || \
            ls -a && pwd && \
            docker build -t ring-books . && \
            docker run --cidfile container_id -p 3000-3001:3000-3001 ring-books

# TODO: Regarding the step below:
#  Right now, this leaves a lot of lein ring servers hanging. I think I need to change to directly use the ring Jetty
#  server!
# TODO: Maybe use a dockerized Jetty server? See my simple Dockerfile in amazon-wishlist/
#      - name: Using SSH, Create a New File in the DigitalOcean Droplet
#        run: |
#          ssh -o StrictHostKeyChecking=no dominik@165.22.76.70 \
#            rm -rf amazon-wishlist && \
#            git clone git@github.com:brgr/amazon-wishlist.git && \
#            cd amazon-wishlist && \
#            LEIN_NO_DEV=true lein ring server-headless

#      - name: Touch some file to check if ssh works
#        run: touch ssh_works.txt
#      - name: Test multi-line bash
#        run: |
#          touch some_file.txt
#          echo "Hello file" > some_other_file.txt

#      - name: Run Tests
#        run: lein test
#        # TODO: probably ssh to my droplet first? then git checkout there, then the action below
#      - name: Build uberjar
#        run: LEIN_NO_DEV=true lein ring server-headless


