name: Build + Deploy
#description: 'Build and deploy to my DigitalOcean droplet'

on:
  push:
    branches:
      - github-actions-test

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
#      - name: Checkout Project
#        uses: actions/checkout@v2

      # TODO: Do the two steps below work? Maybe test on a different branch than master! (e.g. github-actions-test)
      - name: SSH into DigitalOcean Droplet (on 165.22.76.70)
        shell: bash
        env:
          DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS: ${{ secrets.DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS }}
        run: ssh -i <(echo "$DIGITALOCEAN_SSH_KEY_GITHUB_ACTIONS") dominik@165.22.76.70
      - name: Touch some file to check if ssh works
        run: touch ssh_works.txt
      - name: Test multi-line bash
        run: |
          touch some_file.txt
          echo "Hello file" > some_other_file.txt

#      - name: Run Tests
#        run: lein test
#        # TODO: probably ssh to my droplet first? then git checkout there, then the action below
#      - name: Build uberjar
#        run: LEIN_NO_DEV=true lein ring server-headless


